upstream loadbalancer {
    server 172.17.0.1:1901;
    server 172.17.0.1:1902;
    server 172.17.0.1:1903;
    server 172.17.0.1:1904;
    server 172.17.0.1:1905;
}

server {
    location / {
        proxy_pass http://loadbalancer;
    }
}